### PR TITLE
Realign PC API template reflecting aws-parallelcluster changes

### PR DESCRIPTION
**Pull request by ermanno**
### Notes

This patch realigns the PC API template, reflecting the changes in:

https://github.com/aws/aws-parallelcluster/blob/develop/api/infrastructure/parallelcluster-api.yaml

among those, the missing policies that were added in:

https://github.com/aws/aws-parallelcluster/pull/4194

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by sean-smith** [comment]
This file should be unnecessary now that https://github.com/aws/aws-parallelcluster/pull/3886 has been released in `3.1.3`. Suggest removing this file altogether and just referencing the stack on S3 directly.

**Comment by ermanno** [comment]
Talking with @sean-smith it turns out that we don't need this template in the repo, we can use the PI API template hosted on S3. Closing this PR.

**Comment by charlesg3** [comment]
My question is if we need to make corresponding changes in our own infrastructure to reflect the changes made in the PC infrastructure? We use the same imagebuilder process.

**Comment by ermanno** [comment]
Regarding this, afaik (correct me if I am wrong), we reference the template with `TemplateURL: !Sub https://pcluster-manager-${AWS::Region}.s3.${AWS::Region}.amazonaws.com/parallelcluster-api.yaml` so we should "get" the changes made to that template automatically when we deploy the API.

**Pull request closed without merging**
